#ifndef POWERSAVING_H_
#define POWERSAVING_H_

#define POWERSAVING_DISABLE_ALL_MODULES() PR.PRGEN = 0x1f; PR.PRPA = PR.PRPB = 0x07; PR.PRPC = PR.PRPD = PR.PRPE = PR.PRPF = 0x7f

#define POWERSAVING_ENABLE_AES() PR.PRGEN &= ~PR_AES_bm
#define POWERSAVING_DISABLE_AES() PR.PRGEN |= PR_AES_bm
#define POWERSAVING_ENABLE_RTC() PR.PRGEN &= ~PR_RTC_bm
#define POWERSAVING_DISABLE_RTC() PR.PRGEN |= PR_RTC_bm
#define POWERSAVING_ENABLE_ADC() PR.PRPA &= ~PR_ADC_bm
#define POWERSAVING_DISABLE_ADC() PR.PRPA |= PR_ADC_bm
#define POWERSAVING_ENABLE_TWI() PR.PRPC &= ~PR_TWI_bm
#define POWERSAVING_DISABLE_TWI() PR.PRPC |= PR_TWI_bm
#define POWERSAVING_ENABLE_USART() PR.PRPE &= ~PR_USART0_bm
#define POWERSAVING_DISABLE_USART() PR.PRPE |= PR_USART0_bm
#define POWERSAVING_ENABLE_SPIC() PR.PRPC &= ~PR_SPI_bm
#define POWERSAVING_DISABLE_SPIC() PR.PRPC |= PR_SPI_bm
#define POWERSAVING_ENABLE_SPID() PR.PRPD &= ~PR_SPI_bm
#define POWERSAVING_DISABLE_SPID() PR.PRPD |= PR_SPI_bm
#define POWERSAVING_ENABLE_EVSYS() PR.PRGEN &= ~PR_EVSYS_bm
#define POWERSAVING_DISABLE_EVSYS() PR.PRGEN |= PR_EVSYS_bm
#define POWERSAVING_ENABLE_TC0() PR.PRPC &= ~PR_TC0_bm; PR.PRPD &= ~PR_TC0_bm; PR.PRPE &= ~PR_TC0_bm; PR.PRPF &= ~PR_TC0_bm
#define POWERSAVING_DISABLE_TC0() PR.PRPC |= PR_TC0_bm; PR.PRPD |= PR_TC0_bm; PR.PRPE |= PR_TC0_bm; PR.PRPF |= PR_TC0_bm
#define POWERSAVING_ENABLE_TC1() PR.PRPC &= ~PR_TC1_bm; PR.PRPD &= ~PR_TC1_bm; PR.PRPE &= ~PR_TC1_bm; PR.PRPF &= ~PR_TC1_bm
#define POWERSAVING_DISABLE_TC1() PR.PRPC |= PR_TC1_bm; PR.PRPD |= PR_TC1_bm; PR.PRPE |= PR_TC1_bm; PR.PRPF |= PR_TC1_bm

#define DISABLE_JTAG( ) { \
	ENTER_CRITICAL_REGION(); \
	CCP = 0xD8; \
	MCU_MCUCR = MCU_JTAGD_bm; \
	LEAVE_CRITICAL_REGION(); \
}

#endif
